FROM php:8.2-fpm-alpine

RUN apk update && apk add --no-cache \
  freetype-dev \
  jpeg-dev \
  libjpeg-turbo-dev \
  libmcrypt-dev \
  libpng-dev \
  libzip-dev \
  && docker-php-ext-install -j$(nproc) mysqli pdo_mysql zip opcache \
  && docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ \
  && docker-php-ext-install -j$(nproc) gd
