FROM php:5.6-fpm-alpine

RUN apk update && apk add --no-cache \
  freetype-dev \
  jpeg-dev \
  libjpeg-turbo-dev \
  libmcrypt-dev \
  libpng-dev \
  libzip-dev \
  && docker-php-ext-install -j$(nproc) iconv mysqli pdo_mysql zip \
  && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
  && docker-php-ext-install -j$(nproc) gd
